Continuous actions bindings
VowpalWabbit/reinforcement_learning pull request #195
Opened 2020-09-29 15:39 UTC by olgavrou

Mirroring the other bindings from the other loops

Next step:
c# simulator example (in `RLSimulator.cs`) for continuous actions

2020-09-30 18:03 UTC, kumpera requested changes

2020-09-30 18:04 UTC, kumpera commented
Looks great, small issue around build files, everything else are just suggestions.

2020-10-01 14:32 UTC, olgavrou commented on bindings/cs/rl.net.native/rl.net.native.vcxproj
> +    <ClCompile Include="rl.net.continuous_action_response.cc" />
It's a shame the CI doesn't catch this

2020-10-01 14:46 UTC, olgavrou commented on bindings/cs/rl.net/ContinuousActionResponse.cs
> +        public float ChosenActionPdfValue
Replaced and the Get method then becomes `GetContinuousActionChosenActionDensity`

2020-10-01 14:46 UTC, olgavrou commented on bindings/cs/rl.net.native/rl.net.native.vcxproj
> +    <ClCompile Include="rl.net.continuous_action_response.cc" />
Done

2020-10-01 14:46 UTC, olgavrou commented on bindings/cs/rl.net.native/rl.net.continuous_action_response.h
> +    API float GetContinuousChosenAction(reinforcement_learning::continuous_action_response* response);
Replaced

2020-10-01 21:03 UTC, merged