Add Episodic RL Http API interface
VowpalWabbit/reinforcement_learning pull request #544
Opened 2023-01-20 17:59 UTC by homezcx

This PR adds the Episodic RL interface for HTTP_API_HOST. Like the existing EPISODE_EH_* implementation, you will need to specify below:

```
        "http.api.key": "{key}",
	"episode.http.api.host": "{endpoint}",
	"interaction.http.api.host": "{endpoint}",
	"observation.http.api.host": "{endpoint}",
	"episode.sender.implementation": "EPISODE_HTTP_API_SENDER",
	"interaction.sender.implementation": "INTERACTION_HTTP_API_SENDER",
	"observation.sender.implementation": "OBSERVATION_HTTP_API_SENDER",
```

2023-01-20 21:24 UTC, jackgerrits approved these changes

2023-01-23 18:01 UTC, rajan-chari commented
I have a quick question.  This seems to be defining new constants but using them in the same way as before.  Is there a reason to not use the old constants ... in terms of end points etc?

2023-01-23 18:02 UTC, rajan-chari requested changes
I have a quick question. This seems to be defining new constants but using them in the same way as before. Is there a reason to not use the old constants ... in terms of end points etc?

2023-01-23 18:15 UTC, homezcx commented
> I have a quick question. This seems to be defining new constants but using them in the same way as before. Is there a reason to not use the old constants ... in terms of end points etc?

Actually, no specific reason for me not to use the old constants.  I was mainly following the existing pattern put in Episode_EH_* to have EPISODE_APIM_*. If you think we want to clean up in this PR, I can do a follow-up patch too.

2023-01-23 20:49 UTC, rajan-chari commented
> > I have a quick question. This seems to be defining new constants but using them in the same way as before. Is there a reason to not use the old constants ... in terms of end points etc?

> Actually, no specific reason for me not to use the old constants.  I was mainly following the existing pattern put in Episode_EH_* to have EPISODE_APIM_*. If you think we want to clean up in this PR, I can do a follow-up patch too. 

Ah ok.  I see your point.  It seems like these keys and values might add to ambiguity around how to configure.  Perhaps I don't see how we might benefit from having them.  I would love to hear @Wangda's perspective.  If there isn't a compelling reason to have these extra keys, cleaning them up would be ideal.

2023-01-23 23:58 UTC, homezcx commented on rlclientlib/azure_factories.cc
> +  return create_apim_http_api_sender(retval, cfg, api_host, cfg.get_int(name::EPISODE_EH_MAX_HTTP_RETRIES, 4),
Thanks for checking. Fixed.

2023-01-23 23:58 UTC, homezcx commented on include/constants.h
> +const char* const EPISODE_HTTP_API_HOST = "episode.http.api.host";
Thanks for checking. Fixed.

2023-01-23 23:58 UTC, homezcx commented on rlclientlib/azure_factories.cc
> +      cfg.get_int(name::EPISODE_EH_TASKS_LIMIT, 4),
Thanks for checking. Fixed.

2023-01-23 23:58 UTC, homezcx commented on rlclientlib/azure_factories.cc
> +      std::chrono::milliseconds(cfg.get_int(name::EPISODE_EH_MAX_HTTP_RETRY_DURATION_MS, 3600000)), error_cb,
Thanks for checking. Fixed.

2023-01-27 17:01 UTC, rajan-chari approved these changes

2023-01-30 16:46 UTC, merged